CREATE DATABASE CELLS_DEMO;
USE CELLS_DEMO;
CREATE TABLE CELLS_DEMO_DATA (PK INT NOT NULL AUTO_INCREMENT, BALANCE VARCHAR(20) NOT NULL,
DEBT VARCHAR(20) NOT NULL, INTEREST VARCHAR(10), PRIMARY KEY (PK));
SHOW TABLES;
DESCRIBE CELLS_DEMO_DATA;
INSERT INTO CELLS_DEMO_DATA (BALANCE, DEBT, INTEREST) VALUES ('$ - 24,445',
'$ - 1,800', '8.2%');
